interface mixin A {
	constructor();

	attribute double a;
};

interface B {
	constructor();

	attribute A b;
};

partial interface B {
	constructor(float a, double b);

	attribute Int32Array c;
	attribute B c2;
};