typedef (HTMLScriptElement or SVGScriptElement) HTMLOrSVGScriptElement;

typedef (MediaStream or MediaSource or Blob) MediaProvider;

typedef (CanvasRenderingContext2D or ImageBitmapRenderingContext or WebGLRenderingContext or WebGL2RenderingContext or GPUCanvasContext) RenderingContext;

typedef (HTMLImageElement or
         SVGImageElement)? HTMLOrSVGImageElement;

typedef (HTMLOrSVGImageElement or
         HTMLVideoElement or
         HTMLCanvasElement or
         ImageBitmap or
         OffscreenCanvas or
         VideoFrame) CanvasImageSource;

typedef (OffscreenCanvasRenderingContext2D or ImageBitmapRenderingContext or WebGLRenderingContext or WebGL2RenderingContext or GPUCanvasContext) OffscreenRenderingContext;

typedef (DOMString? or Function) TimerHandler;

typedef (CanvasImageSource or
         Blob or
         ImageData) ImageBitmapSource;

typedef (WindowProxy or MessagePort or ServiceWorker)? MessageEventSource;

typedef (Float32Array or sequence<GLfloat>) Float32List;
typedef (Int32Array or sequence<unsigned long long>) Int32List;
typedef (sequence<GLuint> or Uint32Array) Uint32List;