interface mixin A {
	constructor();

	void operationA();

	attribute double a;
};

interface B {
	constructor();

	undefined operationB(float a);

	attribute A b;
};

partial interface B {
	constructor(float a, double b);

	double operationC(optional double a, Int32Array b);

	attribute Int32Array c;
	attribute B c2;
};